# -*- coding: utf-8 -*-
"""Recommender system(Outles).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mcAWZoslxJiYyGx3uvWVPwXNxNj23Rv
"""

!pip install pandas scikit-learn

import pandas as pd

# Load the CSV file, skipping bad lines that cause errors
df = pd.read_csv('/content/styles.csv', on_bad_lines='skip')

# Display the first few rows to verify data loading
print(df.head())

# Display the first few rows
print(df.head())

# Get information about the dataset, including data types and missing values
print(df.info())

# Check for missing values in each column
print(df.isnull().sum())

# Drop rows with missing values in critical columns (e.g., brand, category)
df_cleaned = df.dropna(subset=['brand', 'category', 'price'])

# Alternatively, you can fill missing values
df_cleaned['base_colour'].fillna('Unknown', inplace=True)
df_cleaned['brand'].fillna('Unknown', inplace=True)

# Display the cleaned data
print(df_cleaned.isnull().sum())

!pip install tensorflow

